# Even Fibonacci numbers

# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.
# https://projecteuler.net/problem=2

prev1 = 1
prev2 = 2
sum = 2
while True:
    (prev1, prev2) = (prev2, prev1 + prev2)
    if prev2 > 4000000:
        break
    if prev2 % 2 == 0:
        sum += prev2
print(sum)