# Pentagon numbers

# Problem 44
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; 
# what is the value of D?
# https://projecteuler.net/problem=44

import datetime
import Utilities

start_time = datetime.datetime.now()

i = 1
a = []
need_to_continue = True
while need_to_continue:
    i += 1
    n = ((i * (3 * i - 1)) // 2)
    for j in range (i - 1, 1, -1):
        m = ((j * (3 * j - 1)) // 2)
        if Utilities.IsPentagonalNum(n - m) and Utilities.IsPentagonalNum(n + m):
            a.append(n - m)
            need_to_continue = False
            break

print(a[0])

stop_time = datetime.datetime.now()
print(stop_time - start_time)
