# Triangular, pentagonal, and hexagonal

# Problem 45
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.
# https://projecteuler.net/problem=45

import datetime
import Utilities

start_time = datetime.datetime.now()

max_i = 10000000000
a_tri = Utilities.TriangularNumbers(max_i)
a_pent = Utilities.PentagonalNumbers(max_i)
a_hex = Utilities.HexagonalNumbers(max_i)
a = (a_tri.intersection(a_pent)).intersection(a_hex)
print(a)

stop_time = datetime.datetime.now()
print(stop_time - start_time)
