# Triangular, pentagonal, and hexagonal

# Problem 45
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.
# https://projecteuler.net/problem=45

import datetime
import Utilities

start_time = datetime.datetime.now()

i = 143

while True:
    i += 1
    res = i * (2 * i - 1)
    if Utilities.IsPentagonalNum(res):
        break

print(res)

stop_time = datetime.datetime.now()
print(stop_time - start_time)
